-- ==========================================================================
-- X Account Watcher - Supabase Database Schema
-- Paste this script into Supabase SQL Editor (https://supabase.com/dashboard/project/ohlrsnxhrbosdebkglqd/sql)
-- ==========================================================================

-- 1. Create Accounts Table
CREATE TABLE IF NOT EXISTS public.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  x_user_id TEXT,
  active INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Posts Table (deduplicated by tweet_id and original_url)
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_username TEXT NOT NULL,
  tweet_id TEXT UNIQUE NOT NULL,
  post_type TEXT DEFAULT 'tweet',
  original_content TEXT NOT NULL,
  translated_content TEXT,
  original_lang TEXT DEFAULT 'en',
  original_url TEXT UNIQUE NOT NULL,
  post_date TIMESTAMPTZ NOT NULL,
  fetched_at TIMESTAMPTZ DEFAULT NOW(),
  is_bookmarked INT DEFAULT 0,
  is_deleted INT DEFAULT 0
);

-- 3. Create API Logs Table
CREATE TABLE IF NOT EXISTS public.api_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  endpoint TEXT NOT NULL,
  status_code INT NOT NULL,
  requests_count INT DEFAULT 1,
  rate_limit_remaining INT,
  rate_limit_reset TIMESTAMPTZ,
  note TEXT
);

-- 4. Seed Initial Default Accounts
INSERT INTO public.accounts (username, display_name)
VALUES 
  ('NMTD8', 'NMTD8'),
  ('laivietnam91', 'Lai Vietnam')
ON CONFLICT (username) DO NOTHING;

-- 5. Enable Row Level Security (RLS) & Allow Read/Write
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on accounts" ON public.accounts FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update on accounts" ON public.accounts FOR ALL USING (true);

CREATE POLICY "Allow public select on posts" ON public.posts FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update on posts" ON public.posts FOR ALL USING (true);

CREATE POLICY "Allow public select on api_logs" ON public.api_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update on api_logs" ON public.api_logs FOR ALL USING (true);
